# Generated by Django 4.0.3 on 2022-07-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_white', models.IntegerField(null=True)),
                ('player_black', models.IntegerField(null=True)),
                ('epd', models.TextField(null=True)),
                ('moves', models.TextField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('winner', models.IntegerField(null=True)),
            ],
        ),
    ]
